baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'embeddedboys.org'
theme = 'DoIt'

[params.home.profile]
    gravatarEmail = "writeforever@foxmail.com"
    avatarURL = "/images/embeddedboys.webp"
    avatarLinkURL = ""