baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'embeddedboys.org'
name = "embeddedboys"
theme = 'DoIt'
images = ["/logo.png"]

[params.home.profile]
    gravatarEmail = "writeforever@foxmail.com"
    avatarURL = "/images/embeddedboys.webp"
    avatarLinkURL = ""